FROM nginx:latest
LABEL Description="nginx (a little bit customized)" Vendor="paramtamtam"

COPY ./nginx/html /usr/share/nginx/html
COPY ./nginx/html-errorpages /usr/share/nginx/html-errorpages
COPY ./nginx/errorpages.conf /etc/nginx/errorpages.conf
COPY ./nginx/default.conf /etc/nginx/conf.d/default.conf
