name: Build Docker Image	

on:	
  push:	
#     branches:	
#       - 'image-*'	

jobs:	
  build:	
    runs-on: ubuntu-latest	
    steps:	
    - uses: actions/checkout@v1	
    - name: Build the Docker image	
      run: |
        TAG_NAME=$(echo '${{ github.ref }}' | sed 's/.*image-\(.*\)$/\1/)')
        echo "$TAG_NAME"
      #run: docker build . --file Dockerfile --tag nginx:$(date +%s)
