name: release

on:
  release: # Docs: <https://help.github.com/en/articles/events-that-trigger-workflows#release-event-release>
    types: [published]

jobs: # Docs: <https://git.io/JvxXE>
  docker-build:
    name: Build docker image (${{ matrix.nginx-version }})
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      fail-fast: false
      max-parallel: 6
      matrix:
        nginx-version:
          - latest
          - stable
          - '1.11'
          - '1.12'
          - '1.13'
          - '1.14'
          - '1.15'
          - '1.16'
          - '1.17'
          - '1.18'
          - '1.19'
          - alpine
          - stable-alpine
          - '1.11-alpine'
          - '1.12-alpine'
          - '1.13-alpine'
          - '1.14-alpine'
          - '1.15-alpine'
          - '1.16-alpine'
          - '1.17-alpine'
          - '1.18-alpine'
          - '1.19-alpine'
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Make docker login
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_LOGIN }}" --password-stdin &> /dev/null

      - name: Build docker image
        run: |
          docker build \
            -f ./Dockerfile \
            --build-arg "NGINX_VERSION=${{ matrix.nginx-version }}" \
            --tag "tarampampam/nginx:${{ matrix.nginx-version }}" \
            .

      - name: Push docker image
        run: docker push "tarampampam/nginx:${{ matrix.nginx-version }}"
